#trigger:
#- POC_SMOKE

#trigger:
#- none

pool:
  name: local-docker-agent

steps:
- checkout: self

- script: |
    echo "Docker version:"
    docker --version
  displayName: 'Verify Docker'

- script: |
    docker build -t poc-dev-automation:local .
  displayName: 'Build Docker Image'

- script: |
    docker run --rm poc-dev-automation:local
  displayName: 'Run Docker Container'
