# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- POC_SMOKE

pool:
  name: local-docker-agent   # Windows self-hosted agent

steps:
- checkout: self

- script: |
    python --version
    pip --version
  displayName: 'Verify Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest allure-pytest
  displayName: 'Install dependencies'

- script: |
    pytest .\tests\wja\poc --alluredir=allure-results
  displayName: 'Run POC test cases'

- script: |
    allure generate allure-results -o allure-report --clean
  displayName: 'Generate Allure Report'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'allure-report'
    artifact: 'allure-report'
  displayName: 'Publish Allure Report'
