[pytest]
markers =
    desktop: marks tests related to the WJA Desktop application
    ekcode: marks tests related to EK code validation
    smoke: marks smoke tests for quick validation
    promocode: marks tests related to promo code functionality
    regression: marks regression tests
    unclaimed: marks tests related to unclaimed flow
    mobile: marks mobile automation tests
    android: marks Android-specific tests
    integration: marks integration tests

# Combined the options for better reporting and console visibility
addopts = --html=report.html --self-contained-html --capture=tee-sys -v -s

# Ensure this matches your actual folder name (lowercase 'tests')
testpaths = tests